### ISSUE TITLE
No such file or directory repo-xxxx-core.sqlite

### ISSUE THREAD

**Issue by BillRizer** [PiBa-NL/PiBa-NL-WIKI#1]
Hello, you wiki helped me a lot, but I'm having this problem, do you know something that can help? or some info from when is it creates that .sqlite
my terminal:

```
root@:/usr/local/4sensebeta/4sensebeta # ./build.sh iso
>>> Operation ./build.sh has started at Tue Dec 19 19:00:13 UTC 2017
>>> Building image type(s): iso
>>> Cleaning up previous build environment...Please wait!
>>> Cleaning build directories: Done!
>>> Cleaning previously built kernel stage area...Done!
>>> Cleaning previously built images...Done!
>>> Cleaning previous builder logs...Done!
>>> Cleaning of builder environment has finished.
>>> Obtaining FreeBSD sources (stable/10)...
====>> Removing local changes from git repo https://github.com/teliz/freebsd.git (stable/10)
====>> Removing leftovers from git repo https://github.com/teliz/freebsd.git (stable/10)
====>> Retrieving updates from git repo https://github.com/teliz/freebsd.git (stable/10)
====>> Updating git repo https://github.com/teliz/freebsd.git (stable/10)
====>> Rebasing git repo https://github.com/teliz/freebsd.git (stable/10)
>>> Last known commit Steve Beaver - abe217af4745c9d930f8a0d1f440d7f4854215ee
Updating 4sense-core repository catalogue...
pkg: Repository 4sense-core load error: access repo file(/var/db/pkg/repo-4sense-core.sqlite) failed: No such file or directory
pkg: http://release-staging.netgate.com/ce/packages/4sense_v2_4_2_amd64-core/meta.txz: Operation timed out
repository 4sense-core has no meta file, using default settings
pkg: http://release-staging.netgate.com/ce/packages/4sense_v2_4_2_amd64-core/packagesite.txz: Operation timed out
Unable to update repository 4sense-core
Updating 4sense repository catalogue...
pkg: Repository 4sense load error: access repo file(/var/db/pkg/repo-4sense.sqlite) failed: No such file or directory
pkg: http://release-staging.netgate.com/ce/packages/4sense_v2_4_2_amd64-4sense_v2_4_2/meta.txz: Operation timed out
repository 4sense has no meta file, using default settings
pkg: http://release-staging.netgate.com/ce/packages/4sense_v2_4_2_amd64-4sense_v2_4_2/packagesite.txz: Operation timed out
Unable to update repository 4sense
Updating 4sensebeta-core repository catalogue...
pkg: Repository 4sensebeta-core load error: access repo file(/var/db/pkg/repo-4sensebeta-core.sqlite) failed: No such file or directory

 
```

**Comment by PiBa-NL** [comment]
The .sqlite is created by pkg after downloading the "http://release-staging.netgate.com/ce/packages/4sense_v2_4_2_amd64-core/meta.txz" that should however point to your own repository server.

**Comment by BillRizer** [comment]
I understood, I found these files:
http://files01.netgate.com/pfSense_v2_4_2_amd64-core/

I need to create another repository with them and configure for my build to look in my repository, should I change these values in build.conf, correct?


```
# pkg repo URL
#export PKG_REPO_SERVER_DEVEL="pkg+http://beta.pfsense.org/packages"
#export PKG_REPO_SERVER_RELEASE="pkg+http://pkg.pfsense.org/packages"
#export PKG_REPO_SERVER_STAGING="pkg+http://release-staging.netgate.com/ce/packages"

```

**Comment by PiBa-NL** [comment]
Yes the but you should have most of those packages found in http://files01.netgate.com/pfSense_v2_4_2_amd64-core/ also as a result from the previous commands executed:
```
cd /usr/MyFirewall/ && time ./build.sh --setup-poudriere

cd /usr/MyFirewall/ && ./build.sh --update-poudriere-ports
cd /usr/MyFirewall/ && time ./build.sh -u --update-pkg-repo
```

**Comment by teliz** [comment]
how long does it take for the 
`cd /usr/MyFirewall/ && time ./build.sh --setup-poudriere
`
 to take?
 because I'm 2 hours running it

![capturar](https://user-images.githubusercontent.com/5104527/34263295-15c0d178-e656-11e7-9a9a-8a10d7b8ec42.PNG)

**Comment by BillRizer** [comment]
I`m run :
````
cd /usr/MyFirewall/ && time ./build.sh --setup-poudriere 
````
Perfect, after 5hours.

But, when I run: ````cd /usr/MyFirewall/ && ./build.sh --update-poudriere-ports````
````
root@:/usr/MyFirewall# cd /usr/MyFirewall/ && ./build.sh --update-poudriere-ports
>>> Operation ./build.sh has started at Thu Dec 21 20:56:30 -02 2017
>>> Resetting local changes on ports tree 4sensealfa_devel... Done!
>>> Updating ports tree MyFirewall_devel... Done!
>>> Renaming product ports on MyFirewall_devel... sed: /usr/local/poudriere/ports/MyFirewall_devel/net-mgmt/MyFirewall-pkg-zabbix-agent34/pkg-descr: No such file or directory
sed: /usr/local/poudriere/ports/MyFirewall_devel/net-mgmt/MyFirewall-pkg-zabbix-proxy22/pkg-descr: No such file or directory
sed: /usr/local/poudriere/ports/MyFirewall_devel/net-mgmt/MyFirewall-pkg-zabbix-proxy32/pkg-descr: No such file or directory
sed: /usr/local/poudriere/ports/MyFirewall_devel/net-mgmt/MyFirewall-pkg-zabbix-agent32/pkg-descr: No such file or directory
sed: /usr/local/poudriere/ports/MyFirewall_devel/net-mgmt/MyFirewall-pkg-zabbix-proxy34/pkg-descr: No such file or directory
sed: /usr/local/poudriere/ports/MyFirewall_devel/net-mgmt/MyFirewall-pkg-zabbix-agent22/pkg-descr: No such file or directory
Done!
>>> Operation ./build.sh has ended at Thu Dec 21 20:56:51 -02 2017
````
I'm looking for some wrong configuration but I still can not find it, do you know anything about it?
😄

**Comment by mehmet-tr** [comment]
Hi wiki could give you some idea about the following problem.
Thank you...

====>> Creating core package default-config
====>> Removing immutable flags from /tmp/default-config.TD6fc10
====>> Removing recursively /tmp/default-config.TD6fc10
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
====>> Copying metadata for package default-config
====>> Creating core package default-config
====>> Removing immutable flags from /tmp/default-config.d1EFmui
====>> Removing recursively /tmp/default-config.d1EFmui
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
====>> Copying metadata for package default-config-serial
====>> Creating core package default-config-serial
====>> Removing immutable flags from /tmp/default-config-serial.QWIqxjn
====>> Removing recursively /tmp/default-config-serial.QWIqxjn

**Comment by PiBa-NL** [comment]
Think ive seen those error pass along.. It seems to not cause a problem to get the .iso builded eventually..

**Comment by mehmet-tr** [comment]
iso does not occur

Hi wiki could give you some idea about the following problem.
Thank you...


====>> Removing immutable flags from /tmp/default-config.9ph3sY2
====>> Removing recursively /tmp/default-config.9ph3sY2
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
====>> Copying metadata for package default-config
====>> Creating core package default-config
====>> Removing immutable flags from /tmp/default-config.k6s04QE
====>> Removing recursively /tmp/default-config.k6s04QE
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
====>> Copying metadata for package default-config-serial
====>> Creating core package default-config-serial
====>> Removing immutable flags from /tmp/default-config-serial.FXM2WCr
====>> Removing recursively /tmp/default-config-serial.FXM2WCr
Done!
>>> Installing pkg repository in chroot (/usr/MyFirewall/tmp/stage-dir)...
>>> Installing built ports (packages) in chroot (/usr/MyFirewall/tmp/stage-dir)... Failed!

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated

**Comment by PiBa-NL** [comment]
`Installing built ports (packages) in chroot (/usr/MyFirewall/tmp/stage-dir).. Failed!`
Looks like thats the main issue..

Ive changed my repo config file to not check signatures.. and make sure to add the dns record, and configure nginx to host the package repository. (ive added those steps to the wiki also.)
You might be able to make those repo changes locally manually as well to save a little on build time.. Otherwise start from scratch...

**Comment by mehmet-tr** [comment]
What is my problem ?
====>> Compressing kernel
>>> Cloning everything to /usr/MyFirewall/tmp/stage-dir staging area...mv: rename /usr/MyFirewall/tmp/stage-dir/usr/local/sbin/pfSense-upgrade to /usr/MyFirewall/tmp/stage-dir/usr/local/sbin/MyFirewall-upgrade: No such file or directory
====>> Copying metadata for package rc
====>> Creating core package rc
====>> Removing immutable flags from /tmp/rc.JR7UzWP
====>> Removing recursively /tmp/rc.JR7UzWP
====>> Copying metadata for package base
====>> Creating core package base
====>> Removing immutable flags from /tmp/base.t43reAL
====>> Removing recursively /tmp/base.t43reAL
====>> Copying metadata for package default-config
====>> Creating core package default-config
====>> Removing immutable flags from /tmp/default-config.7uMSjJV
====>> Removing recursively /tmp/default-config.7uMSjJV
====>> Copying metadata for package default-config
====>> Creating core package default-config
====>> Removing immutable flags from /tmp/default-config.pO7vW9u
====>> Removing recursively /tmp/default-config.pO7vW9u
====>> Copying metadata for package default-config-serial
====>> Creating core package default-config-serial
====>> Removing immutable flags from /tmp/default-config-serial.NwycWT9
====>> Removing recursively /tmp/default-config-serial.NwycWT9
Done!
>>> Installing pkg repository in chroot (/usr/MyFirewall/tmp/stage-dir)...
>>> Installing built ports (packages) in chroot (/usr/MyFirewall/tmp/stage-dir)... Failed!

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated
9734.361u 908.101s 17:39.16 1004.8%     55515+749k 366893+3024857io 440612pf+0w
root@MyFirewall:/usr/MyFirewall #

**Comment by mehmet-tr** [comment]
Which directory to download and install FreeBSD-port. I could not understand this information.

== FreeBSD-ports : devel > devel ==

    /sysutils/pfSense-upgrade/files/MyFirewall-upgrade
    /sysutils/pfSense-upgrade/files/MyFirewall-upgrade.wrapper

**Comment by PiBa-NL** [comment]
What does message does the install_pkg_install_ports.txt file contain if it is created.?

Have you set the dns record? Have you configured and started nginx and does it list the ports when visiting the url with a browser?

**Comment by PiBa-NL** [comment]
For the:
> Which directory to download and install FreeBSD-port. I could not understand this information.
> 
> == FreeBSD-ports : devel > devel ==
> 
> /sysutils/pfSense-upgrade/files/MyFirewall-upgrade
> /sysutils/pfSense-upgrade/files/MyFirewall-upgrade.wrapper

This commit has been present in my repository:
https://github.com/PiBa-NL/FreeBSD-ports/commit/4c78df9d6c9ba540d812cde2b67c14b02aeb6529
https://github.com/PiBa-NL/FreeBSD-ports/tree/4c78df9d6c9ba540d812cde2b67c14b02aeb6529/sysutils/pfSense-upgrade/files
But if you forked your own sources from the fresh pfSense repository, then you need to create similar files for the 'YourFirewall' productname..

**Comment by mehmet-tr** [comment]
I'm doing compilation from your repository.

**Comment by PiBa-NL** [comment]
And does the logfile exist? What does it contain? dns and nginx configured?

**Comment by PiBa-NL** [comment]
Without log messages or further info.. I guess its time to close this one.
