### ISSUE TITLE
cd /usr/MyFirewall/ && time ./build.sh -i iso error 

### ISSUE THREAD

**Issue by sreekumarpm** [PiBa-NL/PiBa-NL-WIKI#10]
Dear Piba,

Please help to resolve the issue. 

```
====>> Removing recursively /tmp/default-config.O5sHc55
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
====>> Copying metadata for package default-config
====>> Creating core package default-config
====>> Removing immutable flags from /tmp/default-config.pwAKdlo
====>> Removing recursively /tmp/default-config.pwAKdlo
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
./build.sh: xml: not found
====>> Copying metadata for package default-config-serial
====>> Creating core package default-config-serial
====>> Removing immutable flags from /tmp/default-config-serial.o9wBY8G
====>> Removing recursively /tmp/default-config-serial.o9wBY8G
Done!
>>> Installing pkg repository in chroot (/usr/MyFirewall/tmp/stage-dir)...
>>> Installing built ports (packages) in chroot (/usr/MyFirewall/tmp/stage-dir)... Failed!

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated

```

**Comment by PiBa-NL** [comment]
>  Installing built ports (packages) in chroot (/usr/MyFirewall/tmp/stage-dir)... Failed!

Okay so it failed.. Why? What did you do, what didn't you do?

**Comment by sreekumarpm** [comment]
Installed  pkg, git, poudriere-devel, mkfile, rsync, nginx, unbound, screen, the_silver_searcher, htop
add nginx conf 
 
 location /ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel {
		alias /usr/local/poudriere/data/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel;
		autoindex on;
    }
 location /ce/packages/MyFirewall_MyFirewall_2_4_amd64-core {
		alias /usr/local/poudriere/data/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel;
		autoindex on;
    }
change name server to 127.0.0.01
create unbound.conf 
server IP 192.168.1.25
gateway (Router) 192.168.1.1
server:  
port: 53  
interface: 0.0.0.0  
local-zone: "piba-nl.nl." static  
local-data: "release-staging.piba-nl.nl. IN A 192.168.1.25"  
forward-zone:  
name: "."  
forward-addr: 192.168.1.1@53  
portsnap fetch extract
add signing key 
clone repository 
create zroot 
build.conf same as your repository 
./build.sh --setup-poudriere (finished with no error )
./build.sh --update-poudriere-ports  (finished with no error )
cd /usr/MyFirewall/ && time ./build.sh --update-pkg-repo ( 7 failed ) (approx 4 hours )
./build.sh --build-kernels first getting error again (finished with no error )
./build.sh -i iso getting the above error

**Comment by sreekumarpm** [comment]
Logs 

kernel.MyFirewall.amd64.log
Last Line  ====>> Compressing kernel

installworld.amd64
Last Line >>> Building and installing crypto tools and athstats for amd64 architecture... (Finished - Sun Nov 11 20:18:01 IST 2018)

install_pkg_install_ports.txt

Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel, please wait...
pkg: Error fetching http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel/Latest/pkg.txz: No address record
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel, please wait...
pkg: Error fetching http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel/Latest/pkg.txz: No address record
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel, please wait...
pkg: Error fetching http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel/Latest/pkg.txz: No address record
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.

buildworld.amd64
>>> Sun Nov 11 20:17:15 IST 2018 - Finished build world for amd64 architecture...

**Comment by PiBa-NL** [comment]
> pkg: Error fetching http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel/Latest/pkg.txz: **No address record**

So it seems that though you've configured the DNS record to 'override' my domain, but that it isn't currently actually used when the build is trying to install the ports..

Can you try a?: `drill A release-staging.piba-nl.nl @localhost`

**Comment by sreekumarpm** [comment]
Same Error :(


====>> Copying metadata for package default-config-serial
====>> Creating core package default-config-serial
====>> Removing immutable flags from /tmp/default-config-serial.dCqRjSt
====>> Removing recursively /tmp/default-config-serial.dCqRjSt
Done!
>>> Installing pkg repository in chroot (/usr/MyFirewall/tmp/stage-dir)...
>>> Installing built ports (packages) in chroot (/usr/MyFirewall/tmp/stage-dir)... Failed!

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated

**Comment by PiBa-NL** [comment]
> Same Error :(
So what did you change from before? If nothing then same result is indeed expected..

What does the `drill A release-staging.piba-nl.nl @localhost` show? Does that work?

Anyhow there is no need to show the output if the details are in a different log and apparently nothing changed..

**Comment by sreekumarpm** [comment]
root@freebsd:/usr/MyFirewall # drill A release-staging.piba-nl.nl @localhost
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 24958
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; QUESTION SECTION:
;; release-staging.piba-nl.nl.  IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
piba-nl.nl.     1870    IN      SOA     ns1.he.net. hostmaster.he.net. 2018081305 10800 1800 604800 86400

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: ::1
;; WHEN: Mon Nov 12 00:39:59 2018
;; MSG SIZE  rcvd: 101

**Comment by PiBa-NL** [comment]
That doesn't look good..
Mine shows this:

```
# drill A release-staging.piba-nl.nl @localhost
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 8238
;; flags: qr aa rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; release-staging.piba-nl.nl.  IN      A

;; ANSWER SECTION:
release-staging.piba-nl.nl.     3600    IN      A       192.168.0.40

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.1
;; WHEN: Sun Nov 11 19:14:17 2018
;; MSG SIZE  rcvd: 60
```
See the difference in the answer section.?
So it seems something is wrong with the unbound configuration.

**Comment by sreekumarpm** [comment]
"drill A release-staging.piba-nl.nl @localhost" is not working for me after ./build.sh -i iso 
so I am starting from scratch, please wait

**Comment by sreekumarpm** [comment]
:( same error

**Comment by PiBa-NL** [comment]
Soooooo.. you did the exact same steps and got the same outcome.? What else did you expect?

So i guess we are still also at the same conclusion then.. "Something is wrong with your Unbound / DNS configuration", fix that first.?

**Comment by sreekumarpm** [comment]
Dear PiBa,

Very very thanks for your support. 

I have successfully build ISO, 

I have change nginx.conf as follows  after that build was successfully completed (Before that first location is root   [/usr/local/www/nginx;]. 


location /ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel {
		alias /usr/local/poudriere/data/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel;
		autoindex on;
    }

location /ce/packages/MyFirewall_MyFirewall_2_4_amd64-core {
		alias /usr/local/poudriere/data/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel;
		autoindex on;
    }

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   /usr/local/www/nginx;
            index  index.html index.htm;
        }

**Comment by sreekumarpm** [comment]
Dear PiBa,
I have tried about 30 times and identified the error. 
Some dependencies are missing.
Please check the following dependencies.

"pkg install -y vmdktool py27-salt sudo qemu-user-static sssd pam_ldap pam_mkhomedir gtar xmlstarlet"

If the above dependencies are required for building please update wiki page.

**Comment by PiBa-NL** [comment]
May i ask how/where you identified that these dependencies are needed? I haven't recently build pfSense, but i never seemed to need those items above when i did. Or at least i didn't manually install them.

**Comment by sreekumarpm** [comment]
"cd /usr/MyFirewall/ && time ./build.sh --update-pkg-repo" some packages are failed after this step I have examined the log.  some error messages in the log "/usr/local/poudriere/data/logs/bulk/**" (I don't have log now)
If you want the exact log I will build again from scratch.

**Comment by sreekumarpm** [comment]
Dear Piba,

How to resolve the below issue? 

Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/nonsense_MyFirewall_2_4_amd64-nonsense_MyFirewall_2_4, please wait...
pkg: Error loading trusted certificates

**Comment by msdisatis** [comment]
> 
> 
> Dear Piba,
> 
> How to resolve the below issue?
> 
> Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/nonsense_MyFirewall_2_4_amd64-nonsense_MyFirewall_2_4, please wait...
> pkg: Error loading trusted certificates

I have the same issue.
`pkg: Error loading trusted certificates`

**Comment by sreekumarpm** [comment]
Dear Mohammad,
change signature type signature_type: "**none**",

**Comment by sreekumarpm** [comment]
PiBa-NL commented Nov 17, 2018
May i ask how/where you identified that these dependencies are needed? I haven't recently build pfSense, but i never seemed to need those items above when i did. Or at least i didn't manually install them.

Dear Piba Please find the below depends. 

RUN_DEPENDS=	${LOCALBASE}/bin/git:devel/git \
		${LOCALBASE}/bin/curl:ftp/curl \
		${LOCALBASE}/bin/rsync:net/rsync \
		${LOCALBASE}/bin/screen:sysutils/screen \
		${LOCALBASE}/bin/vmdktool:sysutils/vmdktool \
		${LOCALBASE}/bin/salt:sysutils/py-salt \
		${LOCALBASE}/bin/sudo:security/sudo \
		${LOCALBASE}/sbin/nginx:www/nginx \
		${LOCALBASE}/bin/qemu-arm-static:emulators/qemu-user-static \
		${LOCALBASE}/sbin/sssd:security/sssd \
		${LOCALBASE}/lib/pam_ldap.so:security/pam_ldap \
		${LOCALBASE}/lib/pam_mkhomedir.so:security/pam_mkhomedir \
		${LOCALBASE}/bin/gtar:archivers/gtar \
		${LOCALBASE}/bin/xml:textproc/xmlstarlet
