### ISSUE TITLE
add packages (like squid, snort) into iso 

### ISSUE THREAD

**Issue by sreekumarpm** [PiBa-NL/PiBa-NL-WIKI#13]
Dear Piba,

How can I add packages into ISO?

**Comment by PiBa-NL** [comment]
https://github.com/PiBa-NL/PiBa-NL-WIKI/issues/4

**Comment by sreekumarpm** [comment]
I have add a line in make.conf 
[pfSense-pkg-snort>0:security/pfSense-pkg-snort]
but not working:(
can you please provide a example? 
also after this changing run ./build.sh -i -iso or start from scratch?

**Comment by sreekumarpm** [comment]
Dear Piba, 

I have added the below lines 
pfSense-pkg-snort>0:security/pfSense-pkg-snort \
snort>0:security/snort \
barnyard2>0:security/barnyard2 \
broccoli>0:security/broccoli \
GeoIP>0:net/GeoIP \
libpcap>0:net/libpcap \
mysql56-client>0:databases/mysql56-client \
libdnet>0:net/libdnet \
daq>0:net/daq

All packages are installed but not Showing in GUI  Can you suggest me.

**Comment by tajummal-lab** [comment]
after fork from github/pfsense i`m not able to rename files

**Comment by sreekumarpm** [comment]
Dear Tajummal-lab, 

What is the error?

**Comment by tajummal-lab** [comment]
libreSense-repo-2.4.4_5 depends on file: /usr/local/sbin/libreSense-upgrade - not found

**Comment by tajummal-lab** [comment]
dear SreekumarPM,

i`m fed up with compiling the pfsense 2.4.4
i tried multiple times but fails to compile this 
i`m following the steps provided by  
https://github.com/Augustin-FL/building-pfsense-iso-from-source
what`s yours results and which blogs and pfsense versions you are using

regards: Tajummal
tajummalabbass@gmail.com

**Comment by sreekumarpm** [comment]
follow the steps carefully 
**https://github.com/Augustin-FL/building-pfsense-iso-from-source**
