### ISSUE TITLE
No way to perform pull requests on Wiki ?

### ISSUE THREAD

**Issue by Augustin-FL** [PiBa-NL/PiBa-NL-WIKI#19]
Hello,

How to update your wiki? I made [updated guidelines on how to build pfsense](https://github.com/Augustin-FL/building-pfsense-iso-from-source), but it seems that there is no way to propose wiki pull requests on github...

**Comment by PiBa-NL** [comment]
Thanks @Augustin-FL !
I don't think PR's are possible for the wiki part, hope you don't mind, i added a link to your repository at the top of the wiki page :).

**Comment by Augustin-FL** [comment]
Well, thanks ^^
