### ISSUE TITLE
>>> Installing built ports (packages) in chroot (/usr/MyFirewall/tmp/stage-dir)... Failed!

### ISSUE THREAD

**Issue by TxCorpi0x** [PiBa-NL/PiBa-NL-WIKI#2]
Hi, 
While building from source, at the 
cd /usr/MyFirewall/ && time ./build.sh -i iso

it throws:
>>> Installing built ports (packages) in chroot (/usr/MyFirewall/tmp/stage-dir)... Failed!

when issuing  "pkg update" this is the result:
"
pkg: Repository MyFirewall-core load error: access repo file(/var/db/pkg/repo-MyFirewall-core.sqlite) failed: No such file or directory
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
pkg: Error loading trusted certificates
repository MyFirewall-core has no meta file, using default settings
Fetching packagesite.txz: 100%    2 KiB   1.7kB/s    00:01
pkg: Error loading trusted certificates
Unable to update repository MyFirewall-core
Updating MyFirewall repository catalogue...
pkg: Repository MyFirewall load error: access repo file(/var/db/pkg/repo-MyFirewall.sqlite) failed: No such file or directory
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
pkg: Error loading trusted certificates
repository MyFirewall has no meta file, using default settings
Fetching packagesite.txz: 100%    2 KiB   1.7kB/s    00:01
pkg: Error loading trusted certificates
Unable to update repository MyFirewall
Error updating repositories!

"

**Comment by PiBa-NL** [comment]
`pkg: Error loading trusted certificates`
Ive changed the repo to not check for valid signatures, and added a little info about configuring nginx and dns..

**Comment by TxCorpi0x** [comment]
Thanks for reply, i has  configured nginx on my local repo, but 
http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel
returns 404

**Comment by PiBa-NL** [comment]
Assuming your 'build machine' is behind a main pfSense production router for your network, you could point that 'release-staging.piba-nl.nl' domain name to your own build machine thats now running nginx to host the repository itself. On the main pfSense router ive used services\dnsresolver and added a host-override to point the domain's A record to my buildmachine.. If thats not an option for you i can try and see if i can put the contents of that repository back on the public 'website'.. But you would stay dependent on me updating that repository, and its hosted at a rather slow host..

**Comment by TxCorpi0x** [comment]
Absolutely right, i'm going to be able to build it locally, and the nginx is installed and working, but where can i download the content of staging, pkg and beta package versions?
the official links of the pfsense (netgate.com) is dead

**Comment by PiBa-NL** [comment]
You don't need to download those as your building those yourself as well.?
```
echo ## This will compile all +-500 'ports'..
cd /usr/MyFirewall/ && time ./build.sh --update-pkg-repo
```
