### ISSUE TITLE
building iso

### ISSUE THREAD

**Issue by engmahmoud** [PiBa-NL/PiBa-NL-WIKI#3]
Hi,
all steps done but while i try to run this "cd /usr/MyFirewall/ && time ./build.sh --update-pkg-repo"

i get this error:
[MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel] [2018-03-06_11h02m03s] [pkgrepo:] Queued: 494 Built: 468 Failed: 8   Skipped: 18  Ignored: 0   Tobuild: 0    Time: 03:36:40
[03:36:41] Logs: /usr/local/poudriere/data/logs/bulk/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel/2018-03-06_11h02m03s
[03:36:41] Cleaning up
[03:36:41] Unmounting file systems
>>> ERROR: Something went wrong...
####################################
Something went wrong, check errors!
####################################
NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.
Terminated
10543.707u 2378.397s 3:36:42.11 99.3%   38402+554k 2095984+3493499io 2761672pf+0w
please help my

**Comment by PiBa-NL** [comment]
Check for progress/problems

/usr/local/poudriere/data/logs/bulk/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel/latest/logs
/usr/MyFirewall/logs/poudriere.log

**Comment by engmahmoud** [comment]
this path "/usr/local/poudriere/data/logs/bulk/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel/latest/logs/" have this all log files:
GeoIP-1.6.11.log                                mosh-1.3.2_1.log
MyFirewall-Status_Monitoring-1.7.5.log          mpd5-5.8_3.log
MyFirewall-pkg-AutoConfigBackup-1.50.log        mpfr-3.1.6.log
MyFirewall-pkg-Avahi-1.11_2.log                 mtr-nox11-0.92.log
MyFirewall-pkg-Backup-0.4_2.log                 mysql56-client-5.6.38.log
MyFirewall-pkg-Cron-0.3.7_2.log                 nagios-plugins-2.2.1_5,1.log
MyFirewall-pkg-FTP_Client_Proxy-0.3_3.log       nano-2.8.7.log
MyFirewall-pkg-LCDproc-0.10.5.log               nasm-2.13.01,1.log
MyFirewall-pkg-Lightsquid-3.0.6_4.log           ndpi-2.0.2017.05.23_1.log
MyFirewall-pkg-Notes-0.2.9_2.log                neon-0.30.1.log
MyFirewall-pkg-OpenBGPD-0.11_10.log             net-snmp-5.7.3_17.log
MyFirewall-pkg-Quagga_OSPF-0.6.20_1.log         nettle-3.3.log
MyFirewall-pkg-RRD_Summary-1.3.2_2.log          nginx-1.12.1_2,2.log
MyFirewall-pkg-Service_Watchdog-1.8.4.log       ninja-1.7.2,2.log
MyFirewall-pkg-Shellcmd-1.0.3.log               nmap-7.40_1.log
MyFirewall-pkg-Status_Traffic_Totals-1.2.2.log  norm-1.5r6.log
MyFirewall-pkg-System_Patches-1.1.7.log         nrpe-ssl-2.15_7.log
MyFirewall-pkg-Telegraf-0.4.log                 nspr-4.17.log
MyFirewall-pkg-acme-0.1.30.log                  ntopng-3.0.2017.08.12.log
MyFirewall-pkg-apcupsd-0.3.9_3.log              ntp-4.2.8p10_2.log
MyFirewall-pkg-arping-1.2.2_1.log               nut-2.7.4_4.log
MyFirewall-pkg-bandwidthd-0.7.4_1.log           oniguruma6-6.4.0.log
MyFirewall-pkg-bind-9.11_9.log                  openbgpd-5.2.20121209_2.log
MyFirewall-pkg-blinkled-0.4.7_1.log             openipmi-2.0.21_1.log
MyFirewall-pkg-cellular-1.1.5.log               openldap-client-2.4.45.log
MyFirewall-pkg-darkstat-3.1.3_4.log             openvpn-2.4.4.log
MyFirewall-pkg-freeradius3-0.15.3.log           openvpn-client-export-2.4.4.log
MyFirewall-pkg-frr-0.1.2.log                    p5-Authen-SASL-2.16_1.log
MyFirewall-pkg-gwled-0.2.4_1.log                p5-CGI-4.36.log
MyFirewall-pkg-haproxy-0.54_2.log               p5-Config-IniFiles-2.94.log
MyFirewall-pkg-haproxy-devel-0.54_2.log         p5-Digest-HMAC-1.03_1.log
MyFirewall-pkg-iftop-0.17_2.log                 p5-Error-0.17025.log
MyFirewall-pkg-iperf-2.0.5.5_3.log              p5-ExtUtils-PkgConfig-1.16.log
MyFirewall-pkg-mailreport-3.1.log               p5-GD-2.66.log
MyFirewall-pkg-mtr-nox11-0.85.6_1.log           p5-GSSAPI-0.28_1.log
MyFirewall-pkg-net-snmp-0.1.5.log               p5-HTML-Parser-3.72.log
MyFirewall-pkg-nmap-1.4.4_1.log                 p5-HTML-Tagset-3.20_1.log
MyFirewall-pkg-nrpe-2.3.2_2.log                 p5-Locale-gettext-1.07.log
MyFirewall-pkg-ntopng-0.8.11.log                p5-XML-Parser-2.44.log
MyFirewall-pkg-nut-2.7.4_6.log                  p7zip-16.02.log
MyFirewall-pkg-openvpn-client-export-1.4.14.log pam_ldap-1.8.6_3.log
MyFirewall-pkg-pfBlockerNG-2.1.2_2.log          pam_mkhomedir-0.2.log
MyFirewall-pkg-routed-1.2.3_2.log               pciids-20170916.log
MyFirewall-pkg-siproxd-1.1.3_3.log              pcre-8.40_1.log
MyFirewall-pkg-snmptt-1.0.0.log                 pear-1.10.5.log
MyFirewall-pkg-softflowd-1.2.2.log              pear-Auth_RADIUS-1.1.0.log
MyFirewall-pkg-squid-0.4.42_1.log               pear-Cache_Lite-1.7.16,1.log
MyFirewall-pkg-squidGuard-1.16.4.log            pear-Crypt_CHAP-1.5.0.log
MyFirewall-pkg-stunnel-5.37.log                 pear-HTTP_Request2-2.3.0,1.log
MyFirewall-pkg-sudo-0.3.log                     pear-Mail-1.4.1,1.log
MyFirewall-pkg-syslog-ng-1.14.log               pear-Net_Growl-2.7.0.log
MyFirewall-pkg-tftpd-0.1.3_1.log                pear-Net_IPv6-1.3.0.b2_2.log
MyFirewall-pkg-tinc-1.0.30.log                  pear-Net_SMTP-1.8.0.log
MyFirewall-pkg-zabbix-agent-1.0.1.log           pear-Net_Socket-1.0.14.log
MyFirewall-pkg-zabbix-agent22-1.0.1.log         pear-Net_URL2-2.2.1.log
MyFirewall-pkg-zabbix-agent32-1.0.1.log         pear-XML_RPC2-1.1.3.log
MyFirewall-pkg-zabbix-agent34-1.0.1.log         pecl-intl-3.0.0_10.log
MyFirewall-pkg-zabbix-proxy-1.0.1.log           pecl-radius-1.4.0.b1.log
MyFirewall-pkg-zabbix-proxy22-1.0.1.log         pecl-rrd1-1.1.3.log
MyFirewall-pkg-zabbix-proxy32-1.0.1.log         pecl-ssh2-0-0.13.log
MyFirewall-pkg-zabbix-proxy34-1.0.1.log         pecl-zmq-1.1.3_2.log
MyFirewall-repo-2.4.3.a.20180306.1102.log       perl5-5.24.3.log
MyFirewall-upgrade-0.333.log                    pfsense-bind911-9.11.2.log
aggregate-1.6_1.log                             pftop-0.7_8.log
apache-xml-security-c-1.7.3.log                 php-suhosin-0.9.38_3.log
apcupsd-3.14.14_2.log                           php-xdebug-2.5.0.log
arc-5.21p.log                                   php56-5.6.32.log
argp-standalone-1.3_2.log                       php56-MyFirewall-module-0.57.log
arj-3.10.22_5.log                               php56-bcmath-5.6.32.log
arping-2.15_1.log                               php56-bz2-5.6.32.log
asciidoc-8.6.9_5.log                            php56-ctype-5.6.32.log
ataidle-2.7.2.log                               php56-curl-5.6.32.log
autoconf-2.69_1.log                             php56-dom-5.6.32.log
autoconf-wrapper-20131203.log                   php56-filter-5.6.32.log
automake-1.15.1.log                             php56-ftp-5.6.32.log
automake-wrapper-20131203.log                   php56-gettext-5.6.32.log
avahi-app-0.6.31_5.log                          php56-hash-5.6.32.log
aws-sdk-php-3.29.2.log                          php56-json-5.6.32.log
b43-fwcutter-015.log                            php56-ldap-5.6.32.log
bandwidthd-2.0.1_12.log                         php56-mbstring-5.6.32.log
barnyard2-1.13_1.log                            php56-mcrypt-5.6.32.log
bash-4.4.12_2.log                               php56-mysql-5.6.32.log
beep-1.0_1.log                                  php56-mysqli-5.6.32.log
bind-tools-9.11.2.log                           php56-opcache-5.6.32.log
bind99-9.9.11.log                               php56-openssl-5.6.32.log
binutils-2.28,1.log                             php56-pcntl-5.6.32.log
bird-1.6.3_3.log                                php56-pdo-5.6.32.log
bison-3.0.4,1.log                               php56-pdo_mysql-5.6.32.log
blinkled-0.2.log                                php56-pdo_sqlite-5.6.32.log
boehm-gc-7.6.0.log                              php56-pgsql-5.6.32.log
broccoli-1.97,1.log                             php56-posix-5.6.32.log
bsnmp-regex-0.6_1.log                           php56-readline-5.6.32.log
bsnmp-ucd-0.4.2.log                             php56-session-5.6.32.log
bwi-firmware-kmod-3.130.20.log                  php56-shmop-5.6.32.log
c-ares-1.12.0_2.log                             php56-simplexml-5.6.32.log
c-icap-0.4.4,2.log                              php56-sockets-5.6.32.log
c-icap-modules-0.4.5.log                        php56-sqlite3-5.6.32.log
ca_root_nss-3.34.1.log                          php56-sysvmsg-5.6.32.log
cabextract-1.6.log                              php56-sysvsem-5.6.32.log
cairo-1.14.8_1,2.log                            php56-sysvshm-5.6.32.log
check_reload_status-0.0.8.log                   php56-tokenizer-5.6.32.log
choparp-20150613.log                            php56-xml-5.6.32.log
clamav-0.99.2_5.log                             php56-xmlreader-5.6.32.log
clog-1.0.1_1.log                                php56-xmlwriter-5.6.32.log
cmake-3.9.3.log                                 php56-zlib-5.6.32.log
cpdup-1.18.log                                  pixman-0.34.0.log
cpustats-0.1_1.log                              pkg-1.10.2.log
curl-7.57.0.log                                 pkgconf-1.3.7,1.log
cyrus-sasl-2.1.26_12.log                        png-1.6.34.log
darkstat-3.0.719.log                            popt-1.16_2.log
db5-5.3.28_6.log                                postgresql95-client-9.5.10.log
dbus-1.10.16_1.log                              pound-2.7_1.log
dbus-glib-0.108.log                             protobuf-3.4.1.log
dhcp6-20080615.2.log                            pstree-2.39.log
dhcp_probe-1.3.0_1.log                          py27-Babel-2.3.4.log
dhcpleases-0.3_1.log                            py27-Jinja2-2.9.5.log
dhcpleases6-0.1_2.log                           py27-MarkupSafe-1.0.log
ding-libs-0.5.0.log                             py27-asn1crypto-0.22.0.log
dmidecode-3.1_1.log                             py27-backports_abc-0.5.log
dnsmasq-2.78,1.log                              py27-boto-2.48.0.log
dnstop-20140915.log                             py27-boto3-1.4.0.log
docbook-1.5.log                                 py27-botocore-1.5.86.log
docbook-sgml-4.5_1.log                          py27-certifi-2017.7.27.1.log
docbook-xml-5.0_3.log                           py27-cffi-1.7.0.log
docbook-xsl-1.76.1_3.log                        py27-chardet-3.0.4.log
dpinger-3.0.log                                 py27-cryptography-2.0.3.log
e2fsprogs-libuuid-1.43.6.log                    py27-dateutil-2.6.1.log
errors                                          py27-docutils-0.14.log
expat-2.2.1.log                                 py27-enum34-1.1.6.log
expiretable-0.6_1.log                           py27-futures-3.1.1.log
filterdns-1.0_16.log                            py27-idna-2.5.log
filterlog-0.1_5.log                             py27-ipaddress-1.0.18.log
flex-2.6.1.log                                  py27-jmespath-0.9.0_1.log
fontconfig-2.12.1,1.log                         py27-libcloud-2.2.1.log
fping-3.16.log                                  py27-msgpack-python-0.4.7.log
freeradius3-3.0.15_1.log                        py27-openssl-17.3.0.log
freetype2-2.8.log                               py27-progressbar-2.3_2.log
frr-2.0_1.log                                   py27-pycparser-2.10.log
fusefs-libs-2.9.5.log                           py27-pycrypto-2.6.1_1.log
gawk-4.1.4_1.log                                py27-pysocks-1.6.7.log
gdbm-1.13_1.log                                 py27-pytest-runner-2.11.1.log
getopt-1.1.6.log                                py27-pytz-2017.2,1.log
gettext-runtime-0.19.8.1_1.log                  py27-pyzmq-16.0.2.log
gettext-tools-0.19.8.1.log                      py27-requests-2.18.1_1.log
giflib-5.1.4.log                                py27-s3transfer-0.1.10.log
glib-2.50.2_6,1.log                             py27-salt-2017.7.2.log
gmake-4.2.1_1.log                               py27-serial-3.4.log
gmp-6.1.2.log                                   py27-setuptools-36.2.2.log
gnome_subr-1.0.log                              py27-setuptools_scm-1.15.5.log
go-1.9,1.log                                    py27-singledispatch-3.4.0.3_1.log
go14-1.4.3_2.log                                py27-six-1.11.0.log
gobject-introspection-1.50.0,1.log              py27-speedtest-cli-1.0.6.log
graphviz-2.40.1_2.log                           py27-tornado-4.5.2.log
grepcidr-2.0.log                                py27-urllib3-1.22.log
gtar-1.29.log                                   py27-yaml-3.11_2.log
haproxy-1.7.9.log                               python2-2_3.log
haproxy-devel-1.8.0.log                         python27-2.7.14.log
help2man-1.47.5.log                             qemu-user-static-2.9.94.g20170825_1.log
hiredis-0.13.3.log                              qstats-0.2.log
hostapd-2.6_1.log                               quagga-1.2.1_4.log
hping-2.0.0r3_2,1.log                           radvd-2.17_3.log
htop-2.0.2.log                                  ragel-6.10.log
hyperscan-4.5.2.log                             rate-0.9_1.log
icu-59.1,1.log                                  readline-7.0.3.log
idnkit-1.0_6.log                                redis-3.2.10.log
iftop-1.0.p4.log                                relayd-5.5.20140810_2.log
igmpproxy-0.1_5,1.log                           rhash-1.3.4.log
indexinfo-0.2.6.log                             rrdtool-1.7.0_1.log
intltool-0.51.0_1.log                           rsync-3.1.2_7.log
iperf-2.0.10_1.log                              scons-2.5.1_1.log
iperf3-3.2.log                                  scponly-4.8.20110526_2.log
ipmitool-1.8.18_1.log                           screen-4.6.1_2.log
iprange-1.0.3.log                               sdocbook-xml-1.1_2,2.log
isc-dhcp43-client-4.3.6.log                     siproxd-0.8.2.log
isc-dhcp43-relay-4.3.6.log                      smartmontools-6.5_2.log
isc-dhcp43-server-4.3.6_1.log                   snmptt-1.4_1.log
iso8879-1986_3.log                              socat-1.7.3.2_2.log
jansson-2.10.log                                softflowd-0.9.9_1.log
jbigkit-2.1_1.log                               sqlite3-3.20.1_1.log
jpeg-turbo-1.5.2.log                            squid-3.5.27.log
json-c-0.12.1.log                               squidGuard-1.4_15.log
jsoncpp-1.8.1_1.log                             squid_radius_auth-1.10.log
krb5-1.15.2.log                                 squidclamav-6.16.log
ladvd-1.1.1.log                                 ssh_tunnel_shell-0.1_1.log
lcdproc-0.5.7_2.log                             sshlockout_pf-0.0.2.log
ldb-1.1.29_1.log                                stress-1.0.4.log
ldns-1.7.0_1.log                                strongswan-5.6.0.log
lha-1.14i_7.log                                 stunnel-5.42,1.log
libarchive-3.3.1,1.log                          sudo-1.8.21p2_1.log
libatomic_ops-7.6.0_1.log                       swig13-1.3.40_1.log
libbson-1.8.0.log                               swig30-3.0.12.log
libdaemon-0.14_1.log                            syslog-ng-3.11.1_1.log
libdnet-1.12_1.log                              talloc-2.1.9.log
libedit-3.1.20170329_2,1.log                    tdb-1.3.12,1.log
libevent-2.1.8.log                              telegraf-1.3.0.log
libffi-3.2.1_1.log                              tevent-0.9.31.log
libfontenc-1.1.3_1.log                          texinfo-6.5,1.log
libgcrypt-1.8.1.log                             tftp-hpa-5.2.log
libgd-2.2.4_1,1.log                             tiff-4.0.9.log
libgpg-error-1.27.log                           tinc-1.0.32.log
libhtp-0.5.25.log                               tmux-2.5_1.log
libiconv-1.14_11.log                            trafshow-5.2.3_2,1.log
libidn2-2.0.4.log                               trafshow3-3.1_7,1.log
libinotify-20170711_1.log                       uclcmd-0.1_2.log
libltdl-2.4.6.log                               unbound-1.6.6.log
liblz4-1.8.0,1.log                              unixODBC-2.3.4.log
libmcrypt-2.5.8_3.log                           unzoo-4.4_2.log
libmspack-0.5.log                               vim-lite-8.0.1159.log
libnet-1.1.6_5,1.log                            vm-bhyve-1.1.8.log
libnghttp2-1.26.0.log                           vmdktool-1.4.log
libosip2-5.0.0.log                              vnstat-1.15.log
libpaper-1.1.24.4.log                           voucher-0.1_2.log
libpcap-1.8.1.log                               vstr-1.0.15_1.log
libsigsegv-2.11.log                             w3m-0.5.3.20170102.log
libsodium-1.0.12.log                            webfonts-0.30_13.log
libssh2-1.8.0,3.log                             webp-0.6.0_4.log
libtool-2.4.6.log                               whois-5.2.17.log
libucl-0.8.0.log                                wol-0.7.1_3.log
libunistring-0.9.7.log                          wpa_supplicant-2.6_2.log
libuv-1.14.1.log                                wrapalixresetbutton-0.0.7.log
libxml2-2.9.7.log                               xen-guest-tools-4.6.1.log
libxslt-1.1.29_1.log                            xerces-c3-3.2.0_2.log
libyaml-0.1.6_2.log                             xinetd-2.3.15_2.log
libzmq4-4.2.2.log                               xmlcatmgr-2.2_2.log
lightsquid-1.8_5.log                            xmlcharent-0.3_2.log
lighttpd-1.4.47_1.log                           xmlstarlet-1.6.1.log
links-2.13,1.log                                xorg-macros-1.19.1.log
logrotate-3.9.2.log                             xproto-7.0.31.log
lsof-4.90.p,8.log                               yajl-2.1.0.log
lua52-5.2.4.log                                 zabbix22-agent-2.2.19.log
lua53-5.3.4_1.log                               zabbix22-proxy-2.2.19.log
luajit-2.0.5.log                                zabbix3-agent-3.0.10.log
lzo2-2.10_1.log                                 zabbix3-proxy-3.0.10.log
m4-1.4.18,1.log                                 zabbix32-agent-3.2.7.log
minicron-0.0.2.log                              zabbix32-proxy-3.2.7.log
miniupnpd-1.9.20160113,1.log                    zabbix34-agent-3.4.1.log
mkfontdir-1.0.7.log                             zabbix34-proxy-3.4.1.log
mkfontscale-1.1.2.log                           zip-3.0_1.log
mobile-broadband-provider-info-20170310.log


but this path "/usr/MyFirewall/logs/" is empty

**Comment by engmahmoud** [comment]
now i get this step Done.
but get error in next step "build kernel"
/usr/MyFirewall # cd /usr/MyFirewall/ && time ./build.sh --build-kernels
>>> Operation ./build.sh has started at Wed Mar  7 14:32:19 EET 2018
>>> Obtaining FreeBSD sources (MyFirewall_2_4)...
====>> Cloning git repository https://github.com/PiBa-NL/FreeBSD-src.git (MyFirewall_2_4)
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
====>> ERROR: Execution of 'git clone -q -b MyFirewall_2_4 https://github.com/PiBa-NL/FreeBSD-src.git /usr/MyFirewall/tmp/FreeBSD-src' failed (rc = 128)
>>> ERROR: It was not possible to clone FreeBSD src repo

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated
0.000u 0.059s 51:38.75 0.0%     1709+494k 5+8io 34pf+0w

**Comment by PiBa-NL** [comment]
> Cloning git repository https://github.com/PiBa-NL/FreeBSD-src.git (MyFirewall_2_4)
> error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
> fatal: The remote end hung up unexpectedly

Sounds to me like the connection that git was using broke, maybe some lost packets on the internet.? Simply try again.? And see if it gets any further.? Is your internet connection stable?

**Comment by mehmet-tr** [comment]
Building iso file now make this problem what is it?

====>> Compressing kernel
>>> Cloning everything to /usr/MyFirewall/tmp/stage-dir staging area...mv: rename /usr/MyFirewall/tmp/stage-dir/usr/local/sbin/pfSense-upgrade to /usr/MyFirewall/tmp/stage-dir/usr/local/sbin/MyFirewall-upgrade: No such file or directory
====>> Copying metadata for package rc
====>> Creating core package rc
====>> Removing immutable flags from /tmp/rc.QBhehV9
====>> Removing recursively /tmp/rc.QBhehV9
====>> Copying metadata for package base
====>> Creating core package base
====>> Removing immutable flags from /tmp/base.XMGQ3HY
====>> Removing recursively /tmp/base.XMGQ3HY
====>> Copying metadata for package default-config
====>> Creating core package default-config
====>> Removing immutable flags from /tmp/default-config.pf1jv9Z
====>> Removing recursively /tmp/default-config.pf1jv9Z
====>> Copying metadata for package default-config
====>> Creating core package default-config
====>> Removing immutable flags from /tmp/default-config.7JBsd1D
====>> Removing recursively /tmp/default-config.7JBsd1D
====>> Copying metadata for package default-config-serial
====>> Creating core package default-config-serial
====>> Removing immutable flags from /tmp/default-config-serial.pWsHny9
====>> Removing recursively /tmp/default-config-serial.pWsHny9
Done!
>>> Installing pkg repository in chroot (/usr/MyFirewall/tmp/stage-dir)...
>>> Installing built ports (packages) in chroot (/usr/MyFirewall/tmp/stage-dir)... Failed!

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated
434.941u 150.362s 5:24.63 180.2%	1378+249k 97870+218761io 187801pf+0w

Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel, pl
pkg: Error fetching http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel/Latest/pkg
A pre-built version of pkg could not be found for your system.^M
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.^M
Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel, pl
pkg: Error fetching http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel/Latest/pkg
A pre-built version of pkg could not be found for your system.^M
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.^M
Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel, pl
pkg: Error fetching http://release-staging.piba-nl.nl/ce/packages/MyFirewall_MyFirewall_2_4_amd64-MyFirewall_devel/Latest/pkg
A pre-built version of pkg could not be found for your system.^M
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.^M

**Comment by PiBa-NL** [comment]
- Have you configured a DNS hostoverride on the 'upstream' pfSense / router for that domain to point back to your buildmachine IP-address?
- Can you try and run `pkg install pkg`

**Comment by mehmet-tr** [comment]
root@MyWall:/etc # cat hosts
192.168.1.109 release-staging.piba-nl.nl

hosts file

ping release-staging.piba-nl.nl
PING release-staging.piba-nl.nl (192.168.1.109): 56 data bytes
64 bytes from 192.168.1.109: icmp_seq=0 ttl=64 time=0.113 ms
64 bytes from 192.168.1.109: icmp_seq=1 ttl=64 time=0.093 ms
64 bytes from 192.168.1.109: icmp_seq=2 ttl=64 time=0.123 ms
^C
--- release-staging.piba-nl.nl ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.093/0.110/0.123/0.012 ms


root@MyWall:/etc # pkg install pkg
Updating MyFirewall-core repository catalogue...
MyFirewall-core repository is up to date.
Updating MyFirewall repository catalogue...
MyFirewall repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed

**Comment by PiBa-NL** [comment]
Yes `cat hosts` 'seems' good however it doesn't seem to be used inside the jail where the building happens, (at least my attempt to use the 'hosts' file did not solve the issue of installing ports while the build happens.. which i mention on the wiki as 'not working')

What did work for me was configuring a 'host override' on my upstream pfSense box thats used for internet access..

**Comment by PiBa-NL** [comment]
I've added a little info to the DNS section of the wiki (configure Unbound). Might help you going if the above did not already.
For now it seems time to close this issue.
