### ISSUE TITLE
embedded packages (such as mongodb) into iso

### ISSUE THREAD

**Issue by TxCorpi0x** [PiBa-NL/PiBa-NL-WIKI#4]
Hi, 
I need to have mongodb as a builtin package which does not need to be installed at runtime by pkg, 
what's the best approach?

**Comment by PiBa-NL** [comment]
Try to add it here?: 
https://github.com/pfsense/FreeBSD-ports/blob/8ed3c8937a9d30327679b00e0bc865697455dcb8/security/pfSense/Makefile#L15

**Comment by PiBa-NL** [comment]
me wonders.. Did it work?
Anyhow it seems time to close the issue..

**Comment by TxCorpi0x** [comment]
Worked like a charm,
Thanks

**Comment by sreekumarpm** [comment]
> Worked like a charm,
> Thanks

Dear MehdiValinejad ,

Can you help me to build with **squid, snort**
