### ISSUE TITLE
How Can I Solve This problem? ( Help ME :( )

### ISSUE THREAD

**Issue by lucas0530** [PiBa-NL/PiBa-NL-WIKI#5]
I trying to make iso on pfsense build tool.

root@CUVEPN:/usr/KRSense # cat logs/install_pkg_install_ports.txt 
Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/KRSense_master_amd64-KRSense_devel, please wait...
pkg: Error fetching http://release-staging.piba-nl.nl/ce/packages/KRSense_master_amd64-KRSense_devel/Latest/pkg.txz: No address record
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/KRSense_master_amd64-KRSense_devel, please wait...
pkg: Error fetching http://release-staging.piba-nl.nl/ce/packages/KRSense_master_amd64-KRSense_devel/Latest/pkg.txz: No address record
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
Bootstrapping pkg from pkg+http://release-staging.piba-nl.nl/ce/packages/KRSense_master_amd64-KRSense_devel, please wait...
pkg: Error fetching http://release-staging.piba-nl.nl/ce/packages/KRSense_master_amd64-KRSense_devel/Latest/pkg.txz: No address record
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'

That above log is Error Log.
I added 8.8.8.8 to the resolv.conf file, but I still get the same error.
-> No address record.

please help... 
What should I do?

**Comment by PiBa-NL** [comment]
> Make sure the dns record release-staging.piba-nl.nl A record points back to the nginx pkg webserver machine.. (can use a upstream dnsresolver hostoverride for that)

**Comment by lucas0530** [comment]
Thank you very much for your quick reply.
How do I change the settings of nginx web server?
I set it up as follows:


#```

user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    resolver 172.16.100.44;
    resolver_timeout 10s;  

    upstream backend {
            jdomain release-staging.piba-nl.nl;
            #keepalive 10;   
} 
    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

  location /ce/packages/KRSense_KRSense_2_4_amd64-KRSense_devel {
                alias /usr/local/poudriere/data/packages/KRSense_KRSense_2_4_amd64-KRSense_devel;
                autoindex on;
                proxy_pass http://backend;
    }

  location /ce/packages/PFSense_PFSense_2_4_amd64-core {
                alias /usr/local/poudriere/data/packages/KRSense_KRSense_2_4_amd64-KRSense_devel;
                autoindex on;
                proxy_pass http://backend;
    }


  location /ce/packages/KRSense_master_amd64-core {
                alias /usr/local/poudriere/data/packages/KRSense_KRSense_2_4_amd64-KRSense_devel;
                autoindex on;
                proxy_pass http://backend;
    }

  location /ce/packages/KRSense_master_amd64-KRSense_devel {
                alias /usr/local/poudriere/data/packages/KRSense_KRSense_2_4_amd64-KRSense_devel;
                autoindex on;
                proxy_pass http://backend;
    }
}
}

```


but, After making the change and restarting nginx, the error still appears.
Of course, there is also an / etc / hosts configuration, please give a specific description of how to change the configuration.
Thank you.

**Comment by PiBa-NL** [comment]
Above is formatted like.. unreadable..
If your still stuck at resolving the domain name, then that is **not** solvable with changing /etc/hosts nor changing the nginx config. 
It must be configured on the upstream dns server the buildmachine is using. (thats my experience sofar at least..)

**Comment by lucas0530** [comment]
Everything was resolved by putting 'resolver localhost;' in the 'nginx.conf' configuration file in '/' brackets.

**Comment by PiBa-NL** [comment]
Not sure how changing nginx.conf fixed it for you.. but anyhow thanks for the localhost idea i have added a little text to my wiki DNS section now that would also make it work with a locally installed Unbound..
