### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by sreekupm** [PiBa-NL/PiBa-NL-WIKI#6]
Dear Piba, 

Please help! 
root@freebsd:/usr # cd /usr && git clone -b MyFirewall_2_4 https://github.com/PiBa-NL/pfsense.git MyFirewaall
Cloning into 'MyFirewaall'...
fatal: unable to access 'https://github.com/PiBa-NL/pfsense.git/': SSL certificate problem: self signed certificate in certificate chain

**Comment by sreekupm** [comment]
root@freebsd:/home/sreekumar/pfsense-master # ./build.sh iso
fatal: Not a git repository (or any of the parent directories): .git
>>> Operation ./build.sh has started at Sun Apr 15 23:46:14 IST 2018
>>> Building image type(s): iso
>>> Cleaning up previous build environment...Please wait!
>>> Cleaning build directories: Done!
>>> Cleaning previously built images...Done!
>>> Cleaning previous builder logs...Done!
>>> Cleaning of builder environment has finished.
>>> Obtaining FreeBSD sources (MyFirewall_2_4)...
====>> Cloning git repository https://github.com/PiBa-NL/FreeBSD-src.git (MyFirewall_2_4)
fatal: unable to access 'https://github.com/PiBa-NL/FreeBSD-src.git/': SSL certificate problem: self signed certificate in certificate chain
====>> ERROR: Execution of 'git clone -q -b MyFirewall_2_4 https://github.com/PiBa-NL/FreeBSD-src.git /usr/home/sreekumar/pfsense-master/tmp/FreeBSD-src' failed (rc = 128)
>>> ERROR: It was not possible to clone FreeBSD src repo

####################################
Something went wrong, check errors!
####################################

NOTE: a lot of times you can run './build.sh --clean-builder' to resolve.

Terminated
root@freebsd:/home/sreekumar/pfsense-master #

**Comment by PiBa-NL** [comment]
Are you behind some squid ssl intercepting proxy.? github cert is certainly not selfsigned.. I havent seen this one before.. does a simple 'curl https://github.com' work for you?

**Comment by sreekupm** [comment]
Yes, behind sophos firewall

**Comment by sreekupm** [comment]
root@freebsd:/home/sreekumar/pfsense-master # curl https://github.com
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@freebsd:/home/sreekumar/pfsense-master #

**Comment by PiBa-NL** [comment]
Well.. then probably the easiest way is to make a exception for the build-machine in your sophos firewall.. If thats not possible then you will have to figure out if its possible to install your CA onto the buildmachine or make it trusted in another way. Surely youve got more experence doing such things than i have, and i cant imagine you have to click through security failures on every https site you visit with other client devices ?.

But anyhow configuring proper internet access is outside the scope of building pfSense.
